#which real data coloumns map to simulated data columns in NN mapping

#this is a testing dict.
sims_to_data_feature_mapping: {
        MAG_AUTO_G: MAG_AUTO_G,
        MAG_AUTO_R: MAG_AUTO_R,
        MAG_AUTO_I: MAG_AUTO_I,
        MAG_AUTO_Z: MAG_AUTO_Z,
        MAG_AUTO_Y: MAG_AUTO_Y,
        MAGERR_AUTO_G: MAGERR_AUTO_G,
        MAGERR_AUTO_R: MAGERR_AUTO_R,
        MAGERR_AUTO_I: MAGERR_AUTO_I,
        MAGERR_AUTO_Z: MAGERR_AUTO_Z,
        MAGERR_AUTO_Y: MAGERR_AUTO_Y,
        Z: Z
    }

sims_to_data_feature_mapping_bzzrd: {
        MAG_G: MAG_AUTO_G,
        MAG_R: MAG_AUTO_R,
        MAG_I: MAG_AUTO_I,
        MAG_Z: MAG_AUTO_Z,
        MAG_Y: MAG_AUTO_Y,
        MAGERR_G: MAGERR_AUTO_G,
        MAGERR_R: MAGERR_AUTO_R,
        MAGERR_I: MAGERR_AUTO_I,
        MAGERR_Z: MAGERR_AUTO_Z,
        MAGERR_Y: MAGERR_AUTO_Y,
        Z: REDSHIFT
    }

#pass any parameters to the NN fitting algorithm
matching_params: {
    n_neighbors: 1,
    algorithm: ball_tree
}

#match in healpixPixels at this resolution:
nside_ring_match: 128

#ra-dec ->IP_RING of sims and data. Will match in these pixels
ip_ring: {
    DATA: IP_RING_128,
    SIMS: IP_RING_128
}

#IDs of sims and data. Please don't make these the same!
ID: {
    DATA: COADD_OBJECTS_ID,
    SIMS: ID
}

#matching algorithm, default = sklearn.neighbors.NearestNeighbors
matching_algorithm: sklearn.neighbors.NearestNeighbors

#path to real data
data_path: {
    DATA:
    /Users/hoyleb/DATA/DES/PHOTOZ/DES_training_all_available_spec.fits.IP128.fits,
    SIMS: /Users/hoyleb/DATA/DES/SIMS/small*.IP128.fits
}

output_path: ./knn_sims.fits
